# Generated by Django 5.2.3 on 2025-07-07 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_issue_assignee_user_alter_issue_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='author_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_authors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
